image: python:3.8

pipelines:
    tags:
        '*':
            - step:
                script:
                    - pip install -U tox wheel
                    - tox -e py38
                    - ./deploy.bash
