image: python:3.6

pipelines:
    tags:
        '*':
            - step:
                script:
                    - pip install -U tox wheel
                    - tox -e py36-pandas22
                    - ./deploy.bash
