image: python:3.11

pipelines:
    tags:
        '*':
            - step:
                script:
                    - pip install -U tox build twine
                    - tox -e py311
                    - ./deploy.bash
